/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEverestVaultMulti,
  IEverestVaultMultiInterface,
} from "../../../src/LoopTester.sol/IEverestVaultMulti";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "borrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IEverestVaultMulti__factory {
  static readonly abi = _abi;
  static createInterface(): IEverestVaultMultiInterface {
    return new Interface(_abi) as IEverestVaultMultiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEverestVaultMulti {
    return new Contract(address, _abi, runner) as unknown as IEverestVaultMulti;
  }
}
