/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  LoopTester,
  LoopTesterInterface,
} from "../../../src/LoopTester.sol/LoopTester";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_vault",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "testBorrowThenDeposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount2",
        type: "uint256",
      },
    ],
    name: "testDoubleBorrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "vault",
    outputs: [
      {
        internalType: "contract IEverestVaultMulti",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161033c38038061033c83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6102a9806100936000396000f3fe6080604052600436106100345760003560e01c806352d3037a14610039578063842f1c871461005b578063fbfa77cf1461006e575b600080fd5b34801561004557600080fd5b50610059610054366004610225565b6100aa565b005b610059610069366004610251565b610179565b34801561007a57600080fd5b5060005461008e906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b600054604051630ecbcdab60e01b815260048101859052602481018490526001600160a01b0390911690630ecbcdab90604401600060405180830381600087803b1580156100f757600080fd5b505af115801561010b573d6000803e3d6000fd5b5050600054604051630ecbcdab60e01b815260048101879052602481018590526001600160a01b039091169250630ecbcdab9150604401600060405180830381600087803b15801561015c57600080fd5b505af1158015610170573d6000803e3d6000fd5b50505050505050565b600054604051630ecbcdab60e01b815260048101849052602481018390526001600160a01b0390911690630ecbcdab90604401600060405180830381600087803b1580156101c657600080fd5b505af11580156101da573d6000803e3d6000fd5b505060005460405163b6b55f2560e01b8152600481018690526001600160a01b03909116925063b6b55f25915083906024016000604051808303818588803b15801561015c57600080fd5b60008060006060848603121561023a57600080fd5b505081359360208301359350604090920135919050565b6000806040838503121561026457600080fd5b5050803592602090910135915056fea26469706673582212207c46c059407e5b6810add738164365f2980bedf58f3077c219b5cb6bd532d25764736f6c63430008180033";

type LoopTesterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LoopTesterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LoopTester__factory extends ContractFactory {
  constructor(...args: LoopTesterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _vault: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_vault, overrides || {});
  }
  override deploy(
    _vault: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_vault, overrides || {}) as Promise<
      LoopTester & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LoopTester__factory {
    return super.connect(runner) as LoopTester__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LoopTesterInterface {
    return new Interface(_abi) as LoopTesterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LoopTester {
    return new Contract(address, _abi, runner) as unknown as LoopTester;
  }
}
