/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEverest,
  IEverestInterface,
} from "../../../../src/mocks/LoopSameBlock.sol/IEverest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "borrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IEverest__factory {
  static readonly abi = _abi;
  static createInterface(): IEverestInterface {
    return new Interface(_abi) as IEverestInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IEverest {
    return new Contract(address, _abi, runner) as unknown as IEverest;
  }
}
