/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  LoopSameBlock,
  LoopSameBlockInterface,
} from "../../../../src/mocks/LoopSameBlock.sol/LoopSameBlock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "vault",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "borrowThenDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "vault",
        type: "address",
      },
    ],
    name: "depositTo",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610218806100206000396000f3fe60806040526004361061002d5760003560e01c8063779b8cfb14610039578063b760faf91461005b57600080fd5b3661003457005b600080fd5b34801561004557600080fd5b50610059610054366004610196565b61006e565b005b6100596100693660046101c0565b610123565b60405163317afabb60e21b81526004810182905282906001600160a01b0382169063c5ebeaec90602401600060405180830381600087803b1580156100b257600080fd5b505af11580156100c6573d6000803e3d6000fd5b50505050806001600160a01b031663d0e30db0836040518263ffffffff1660e01b81526004016000604051808303818588803b15801561010557600080fd5b505af1158015610119573d6000803e3d6000fd5b5050505050505050565b806001600160a01b031663d0e30db0346040518263ffffffff1660e01b81526004016000604051808303818588803b15801561015e57600080fd5b505af1158015610172573d6000803e3d6000fd5b505050505050565b80356001600160a01b038116811461019157600080fd5b919050565b600080604083850312156101a957600080fd5b6101b28361017a565b946020939093013593505050565b6000602082840312156101d257600080fd5b6101db8261017a565b939250505056fea2646970667358221220c12bf4faff9f833923503857751da7222bdfe115beb156df79cd8e25dc9f8d8264736f6c63430008180033";

type LoopSameBlockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LoopSameBlockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LoopSameBlock__factory extends ContractFactory {
  constructor(...args: LoopSameBlockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LoopSameBlock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LoopSameBlock__factory {
    return super.connect(runner) as LoopSameBlock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LoopSameBlockInterface {
    return new Interface(_abi) as LoopSameBlockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): LoopSameBlock {
    return new Contract(address, _abi, runner) as unknown as LoopSameBlock;
  }
}
